### ISSUE TITLE
Remove getDraftOrVersionOfEntry

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/craft-dev#229]
`getDraftOrVersionOfEntry` is a holdover from a previous way of handling previews in craft. The recent headless mode (with `x-craft-*` tokens) handles things automatically. This should mean that we can remove `getDraftOrVersionOfEntry`.

**Tips:**

- Try removing this gradually to confirm that previews still work for each content type

**Comment by davidrapson** [comment]
Tagged this as "good first issue", but this would also be a good one to pair on as there might be a couple of hurdles in testing this locally.

**Comment by mattandrews** [comment]
Definitely seen a fair amount of 500 errors when previewing content where you're midway through adding a required field, wonder if we have some way of fixing that at the same time.

**Comment by davidrapson** [comment]
Maybe, but might add a new issue for that as that's probably a bit beyond a "good first issue".

**Comment by davidrapson** [comment]
Resolved by https://github.com/biglotteryfund/craft-dev/pull/258
