### ISSUE TITLE
Remove redundant field from API and template

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/craft-dev#246]
There's a now-unused field called `heading` in the Flexible Content transformer: https://github.com/biglotteryfund/craft-dev/blob/master/lib/ContentHelpers.php#L210 as a result of this change: https://github.com/biglotteryfund/craft-dev/pull/241

This corresponds to a frontend template here: https://github.com/biglotteryfund/blf-alpha/blob/master/views/components/flexible-content-next/macro.njk#L48

If the template is changed to `part.title` (which is the same text as `part.heading`) then we can remove the line in `ContentHelpers.php` (eg. the whole block can just be `$data = [];`).

**Comment by davidrapson** [comment]
Closed in https://github.com/biglotteryfund/craft-dev/pull/248
